import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./Components.tsx/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body className="bg-[#012745] text-white">
        <NavBar />
        <main className="pt-20">{children}</main>
      </body>
    </html>
  );
}